### ISSUE TITLE
ci: cache Cypress installation

### ISSUE THREAD

**Issue by LayZeeDK** [LayZeeDK/energy-insights#9]
Cache Cypress' cache folder for installation on GitHub runners.

**Comment by geromegrignon** [comment]
Hi @LayZeeDK,

as the project isn't open sourced (in order to contribute), here is a snippet for you to cache Cypress installation: 

```yml
- uses: actions/cache@v3
  with:
     path: /home/runner/.cache/Cypress
     key: cypress-binary-${{ hashFiles('**/package-lock.json') }}
```

**Comment by LayZeeDK** [comment]
Thank you, @geromegrignon

Is there a command to list the Cypress cache directory similar to "yarn cache dir"? 


Is this a Cypress installation cache, test cache, or something else?

**Comment by geromegrignon** [comment]
You can run `npx cypress cache path` to get the path: https://docs.cypress.io/guides/guides/command-line#cypress-cache-command

That's the path of Cypress binaries: https://docs.cypress.io/guides/getting-started/installing-cypress#Install-binary

**Comment by LayZeeDK** [comment]
By the way, this project's license is [MIT as stated in package.json](https://github.com/LayZeeDK/energy-insights/blob/2ae91d0c0fb864c994778a23c0d91a4e693440d9/package.json#L4) but I will make it more discoverable in a license file, see #11.

**Comment by LayZeeDK** [comment]
> You can run `npx cypress cache path` to get the path: [docs.cypress.io/guides/guides/command-line#cypress-cache-command](https://docs.cypress.io/guides/guides/command-line#cypress-cache-command)
> 
> That's the path of Cypress binaries: [docs.cypress.io/guides/getting-started/installing-cypress#Install-binary](https://docs.cypress.io/guides/getting-started/installing-cypress#Install-binary)

Thank you very much, this is exactly what I'm looking for!

**Comment by LayZeeDK** [comment]
@geromegrignon 

How would I set up a job that installed Cypress using the cache without having to depend on `node_modules` and `yarn install`? Would I upload a build artifact from the `build` step, then download and serve the bundle statically in the `e2e` step and run the `cypress` command directly, after restoring from cache?

**Comment by LayZeeDK** [comment]
> You can run `npx cypress cache path` to get the path: [docs.cypress.io/guides/guides/command-line#cypress-cache-command](https://docs.cypress.io/guides/guides/command-line#cypress-cache-command)

Hmm, it's kind of a pain that you need the `cypress` binary to get the Cypress cache directory path 😅

**Comment by geromegrignon** [comment]
> > You can run `npx cypress cache path` to get the path: [docs.cypress.io/guides/guides/command-line#cypress-cache-command](https://docs.cypress.io/guides/guides/command-line#cypress-cache-command)
> 
> Hmm, it's kind of a pain that you need the `cypress` binary to get the Cypress cache directory path 😅

You can use `CYPRESS_CACHE_FOLDER` env variable to set a custom path.

```yml
on: [push, pull_request, workflow_dispatch]
env:
  CYPRESS_CACHE_FOLDER: cypress/cache

jobs:
  e2e-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: exercices/steps
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: cypress/cache
          key: cypress-binary-${{ hashFiles('**/package-lock.json') }}
```

I will have to dive in for the previous question
